include: ["_pages"]

# Dependencies
markdown: kramdown

# Permalinks
permalink: pretty

# Setup
title: Lluis Guirado
tagline: "A Jekyll theme"
description: 'Product engineer & maker'
github_repo: https://github.com/Petrus230/petrus230.github.io
url: https://lluisguirado.com
baseurl: ""

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts

plugins:
  - jekyll-date-localization

livereload: true
port: 8080
