include: ["_pages"]

# Dependencies
markdown: kramdown

# Permalinks
permalink: pretty

# Setup
title: Lluis Guirado
tagline: "A Jekyll theme"
description: 'Product engineer & maker'
github_repo: https://github.com/Petrus230/petrus230.github.io
linkedin_username: lluisguirado
user_name: lluis guirado
user_email: lluis.guivi@gmail.com
url: https://lluisguirado.com
baseurl: ""

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts

plugins:
  - jekyll-polyglot
  - jekyll-redirect-from
  - jekyll-date-localization
  - jekyll-minifier
  - jekyll-sitemap
  - jekyll-feed

livereload: true
port: 8080

languages: ["en", "ca", "es"]
langsep: ·
default_lang: en
exclude_from_localization: ["javascript", "images", "css", "public", "sitemap", "assets"]
parallel_localization: false
lang_from_path: true
